In [18]:
import pandas as pd
import numpy as np

## Coffee Analysis 
#### Author: Hana Makhlouf

* Using a dataset from kaggle https://www.kaggle.com/ankurchavda/coffee-beans-reviews-by-coffee-quality-institute

#### Process I am following:

* understanding the data
* cleaning the data
* visualising the data

In [19]:
# load csv file
data = pd.read_csv("Coffee-modified.csv")

In [20]:
data.head(10)

,ID,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0.0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,2,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1.0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,3,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0.0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,4,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2.0,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,5,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2.0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
5,6,Arabica,ji-ae ahn,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,...,Bluish-Green,1.0,"September 3rd, 2014",Specialty Coffee Institute of Asia,726e4891cf2c9a4848768bd34b668124d12c4224,b70da261fcc84831e3e9620c30a8701540abc200,m,NaN,NaN,NaN
6,7,Arabica,hugo valdivia,Peru,NaN,NaN,hvc,NaN,richmond investment-coffee department,NaN,...,Bluish-Green,0.0,"September 17th, 2013",Specialty Coffee Institute of Asia,726e4891cf2c9a4848768bd34b668124d12c4224,b70da261fcc84831e3e9620c30a8701540abc200,m,NaN,NaN,NaN
7,8,Arabica,ethiopia commodity exchange,Ethiopia,aolme,NaN,c.p.w.e,010/0338,NaN,1570-1700,...,NaN,0.0,"September 2nd, 2011",Ethiopia Commodity Exchange,a176532400aebdc345cf3d870f84ed3ecab6249e,61bbaf6a9f341e5782b8e7bd3ebf76aac89fe24b,m,1570.0,1700.0,1635.0
8,9,Arabica,ethiopia commodity exchange,Ethiopia,aolme,NaN,c.p.w.e,010/0338,NaN,1570-1700,...,NaN,0.0,"September 2nd, 2011",Ethiopia Commodity Exchange,a176532400aebdc345cf3d870f84ed3ecab6249e,61bbaf6a9f341e5782b8e7bd3ebf76aac89fe24b,m,1570.0,1700.0,1635.0
9,10,Arabica,diamond enterprise plc,Ethiopia,tulla coffee farm,NaN,tulla coffee farm,2014/15,diamond enterprise plc,1795-1850,...,Green,4.0,"March 29th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1795.0,1850.0,1822.5

In [21]:
#understand the dimensions and info of the data
data.info
data.shape
data.dtypes

ID                        object
Species                   object
Owner                     object
Country.of.Origin         object
Farm.Name                 object
Lot.Number                object
Mill                      object
ICO.Number                object
Company                   object
Altitude                  object
Region                    object
Producer                  object
Number.of.Bags            object
Bag.Weight                object
In.Country.Partner        object
Harvest.Year              object
Grading.Date              object
Owner.1                   object
Variety                   object
Processing.Method         object
Aroma                     object
Flavor                    object
Aftertaste                object
Acidity                   object
Body                     float64
Balance                  float64
Uniformity               float64
Clean.Cup                float64
Sweetness                float64
Cupper.Points             object
Total.Cup.Points          object
Moisture                  object
Category.One.Defects      object
Quakers                   object
Color                     object
Category.Two.Defects     float64
Expiration                object
Certification.Body        object
Certification.Address     object
Certification.Contact     object
unit_of_measurement       object
altitude_low_meters      float64
altitude_high_meters     float64
altitude_mean_meters     float64
dtype: object

In [22]:
#find how many cells are empty in each column
null_columns=data.columns[data.isnull().any()]
data[null_columns].isnull().sum()

ID                          7
Owner                       9
Country.of.Origin           3
Farm.Name                 358
Lot.Number               1043
Mill                      312
ICO.Number                150
Company                   214
Altitude                  227
Region                     62
Producer                  235
Number.of.Bags              5
Bag.Weight                  5
In.Country.Partner          5
Harvest.Year               53
Grading.Date                6
Owner.1                    14
Variety                   209
Processing.Method         160
Aroma                       8
Flavor                     10
Aftertaste                 10
Acidity                    10
Body                       10
Balance                    10
Uniformity                 10
Clean.Cup                  12
Sweetness                  11
Cupper.Points              11
Total.Cup.Points           11
Moisture                   11
Category.One.Defects       11
Quakers                    12
Color                     227
Category.Two.Defects       12
Expiration                 12
Certification.Body         12
Certification.Address      12
Certification.Contact      12
unit_of_measurement        12
altitude_low_meters       238
altitude_high_meters      238
altitude_mean_meters      238
dtype: int64

In [23]:
#delete any row that has an empty ID 
data.dropna(subset = ["ID"], inplace=True)

In [24]:
data[null_columns].isnull().sum()

ID                          0
Owner                       8
Country.of.Origin           1
Farm.Name                 356
Lot.Number               1041
Mill                      310
ICO.Number                147
Company                   210
Altitude                  223
Region                     58
Producer                  231
Number.of.Bags              1
Bag.Weight                  1
In.Country.Partner          1
Harvest.Year               49
Grading.Date                2
Owner.1                    10
Variety                   205
Processing.Method         156
Aroma                       4
Flavor                      4
Aftertaste                  4
Acidity                     4
Body                        4
Balance                     4
Uniformity                  4
Clean.Cup                   5
Sweetness                   4
Cupper.Points               4
Total.Cup.Points            4
Moisture                    4
Category.One.Defects        4
Quakers                     5
Color                     220
Category.Two.Defects        5
Expiration                  5
Certification.Body          5
Certification.Address       5
Certification.Contact       5
unit_of_measurement         5
altitude_low_meters       231
altitude_high_meters      231
altitude_mean_meters      231
dtype: int64

In [25]:
#change formats of numeric columns to float instead of object
data["Aroma"] = data["Aroma"].astype(str).astype(float)
data["Flavor"] = data["Flavor"].astype(str).astype(float)
data["Aftertaste"] = data["Aftertaste"].astype(str).astype(float)
data["Acidity"] = data["Acidity"].astype(str).astype(float)
data["Body"] = data["Body"].astype(str).astype(float)
data["Balance"] = data["Balance"].astype(str).astype(float)
data["Uniformity"] = data["Uniformity"].astype(str).astype(float)
data["Clean.Cup"] = data["Clean.Cup"].astype(str).astype(float)
#data["Cupper.Points"] = data["Cupper.Points"].astype(str).astype(float)
#data["Total.Cup.Points"] = data["Total.Cup.Points"].astype(str).astype(float)
#data["Moisture"] = data["Moisture"].astype(str).astype(float)
print(data.dtypes)

ID                        object
Species                   object
Owner                     object
Country.of.Origin         object
Farm.Name                 object
Lot.Number                object
Mill                      object
ICO.Number                object
Company                   object
Altitude                  object
Region                    object
Producer                  object
Number.of.Bags            object
Bag.Weight                object
In.Country.Partner        object
Harvest.Year              object
Grading.Date              object
Owner.1                   object
Variety                   object
Processing.Method         object
Aroma                    float64
Flavor                   float64
Aftertaste               float64
Acidity                  float64
Body                     float64
Balance                  float64
Uniformity               float64
Clean.Cup                float64
Sweetness                float64
Cupper.Points             object
Total.Cup.Points          object
Moisture                  object
Category.One.Defects      object
Quakers                   object
Color                     object
Category.Two.Defects     float64
Expiration                object
Certification.Body        object
Certification.Address     object
Certification.Contact     object
unit_of_measurement       object
altitude_low_meters      float64
altitude_high_meters     float64
altitude_mean_meters     float64
dtype: object

In [26]:
#remove kg and lb from weight of bag and change column type to int

In [27]:
#fix harvest year format

In [28]:
#remove lot.number as its mostly empty
del data['Lot.Number']

In [29]:
#data.head(5)

In [30]:
format_dict = {'Flavor':'${:.2f}'} #showing aroma values to 2 decimal places
data.head().style.format(format_dict).highlight_max(color='darkgreen').highlight_min(color='#ff0000')

In [ ]:
from pandas_profiling import ProfileReport
prof = ProfileReport(data)
prof.to_file(output_file='report.html')

HBox(children=(FloatProgress(value=0.0, description='Summarize dataset', max=58.0, style=ProgressStyle(descrip…

In [ ]:
#looking at correlation between flavor, aroma, aftertaste, acidity, body, balance
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
matplotlib.style.use('ggplot')

plt.scatter(data['Aroma'], data['Flavor'])
plt.xlabel('Aroma')
plt.ylabel('Flavor')
plt.title('Correlation between Aroma and Flavor in over 1000 types of coffee')
plt.grid(True)
plt.show()

In [ ]:
#correlation matrix plot
import seaborn as sns

corr = data.corr()
ax = sns.heatmap(
    corr, 
    vmin=-1, vmax=1, center=0,
    cmap=sns.diverging_palette(20, 220, n=200),
    square=True
)
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
);

In [ ]:
#scatter plot with size and colour for specific parameters
#exploring these correlations in more depth

# Step 1 - Make a scatter plot with square markers, set column names as labels

def heatmap(x, y, size):
    fig, ax = plt.subplots()
    
    # Mapping from column names to integer coordinates
    x_labels = [v for v in sorted(x.unique())]
    y_labels = [v for v in sorted(y.unique())]
    x_to_num = {p[1]:p[0] for p in enumerate(x_labels)} 
    y_to_num = {p[1]:p[0] for p in enumerate(y_labels)} 
    
    size_scale = 500
    
    # Show column labels on the axes
    ax.set_xticks([x_to_num[v] for v in x_labels])
    ax.set_xticklabels(x_labels, rotation=45, horizontalalignment='right')
    ax.set_yticks([y_to_num[v] for v in y_labels])
    ax.set_yticklabels(y_labels)
    
    #make sure the boxes are not on the axes but inside the grid
    ax.grid(False, 'major')
    ax.grid(True, 'minor')
    ax.set_xticks([t + 0.5 for t in ax.get_xticks()], minor=True)
    ax.set_yticks([t + 0.5 for t in ax.get_yticks()], minor=True)

    #start axes from -0.5
    ax.set_xlim([-0.5, max([v for v in x_to_num.values()]) + 0.5]) 
    ax.set_ylim([-0.5, max([v for v in y_to_num.values()]) + 0.5])

    n_colors = 256 # Use 256 colors for the diverging color palette
    palette = sns.diverging_palette(20, 220, n=n_colors) # Create the palette
    color_min, color_max = [-1, 1] # Range of values that will be mapped to the palette, i.e. min and max possible correlation
    
    def value_to_color(val):
        val_position = float((val - color_min)) / (color_max - color_min) # position of value in the input range, relative to the length of the input range
        ind = int(val_position * (n_colors - 1)) # target index in the color palette
        return palette[ind]
    
    #color not workingh here - this is meant to use gradient for the color of the blocks
    ax.scatter(
        x=x.map(x_to_num),
        y=y.map(y_to_num),
        s=size * size_scale,
        #c=color.apply(value_to_color), # Vector of square color values, mapped to color palette
        marker='s'
    )


columns = ['Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Sweetness', 'Uniformity'] 
corr = data[columns].corr()
corr = pd.melt(corr.reset_index(), id_vars='index') # Unpivot the dataframe, so we can get pair of arrays for x and y
corr.columns = ['x', 'y', 'value']
heatmap(
    x=corr['x'],
    y=corr['y'],
    size=corr['value'].abs()
)